### ISSUE TITLE
RotateRight actually rotates left

### ISSUE THREAD

**Issue by jl0pd** [Entomy/Tooling#1]
Function `RotateRight` calls `RotateLeft` which I think is typo, since `RotateLeft` also calls `RotateLeft`

https://github.com/Entomy/Numbersome/blob/70740267c61036b2e90f6a935b7d13c5683bb847/Numbersome/RotateRight.cs#L13

**Comment by Entomy** [comment]
You are correct. This is a copypasta error.

**Comment by Entomy** [comment]
Fixed and uploaded a new package. Thank you for letting me know!
